// Embeds the canonical CodeMoot docs into the MCP server at build time, so connected LLMs
// can self-serve accurate usage and configuration knowledge from any install location.
//
// Every doc is discovered by GLOB — a doc that exists is always reachable. A hand-picked
// list is how `handoff-contracts` (the exact agent JSON envelope) stayed invisible to
// connected LLMs while the knowledge sat in the repository the whole time.
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..', '..', '..');
const docsRoot = resolve(repoRoot, 'docs');

/** Topic slugs that must exist and keep their exact names (tool descriptions cite them). */
const REQUIRED_TOPICS = ['configuration', 'autonomous-runner', 'handoff-contracts', 'quickstart'];

/** Ordered first in the topic list: what an agent needs before doing anything. */
const PRIORITY = new Map([
  ['configuration', 0],
  ['autonomous-runner', 1],
  ['handoff-contracts', 2],
  ['quickstart', 3],
]);

/** `review-workflow-merge-gate.md` -> `merge-gate`; `workflow/protocol.md` -> `workflow-protocol`. */
function toTopic(relativePath) {
  return relativePath.replace(/\.md$/, '').replace(/\//g, '-').toLowerCase();
}

/** The shortened form, used only when it does not collide with another doc's slug. */
function toShortTopic(topic) {
  return topic.replace(/^review-workflow-/, '');
}

function firstMeaningfulLine(markdown) {
  for (const line of markdown.split('\n')) {
    const trimmed = line.replace(/^#+\s*/, '').trim();
    if (trimmed.length > 0) return trimmed.slice(0, 160);
  }
  return 'CodeMoot documentation';
}

function collectMarkdown(directory) {
  const found = [];
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    const full = join(directory, entry.name);
    if (entry.isDirectory()) {
      found.push(...collectMarkdown(full));
    } else if (entry.name.endsWith('.md')) {
      found.push(full);
    }
  }
  return found;
}

const docs = new Map();
// The README is the `quickstart` topic; everything under docs/ carries its derived slug.
docs.set('quickstart', {
  path: resolve(repoRoot, 'README.md'),
  summary: 'Project README: install, commands, presets',
});
const discovered = collectMarkdown(docsRoot)
  .sort()
  .map((path) => ({ path, full: toTopic(relative(docsRoot, path)) }));
// A shortened slug is used only when it is unique AND does not shadow another doc's full
// slug — `review-workflow-configuration.md` must never clobber `configuration.md`.
const fullSlugs = new Set(discovered.map((entry) => entry.full));
const shortCounts = new Map();
for (const entry of discovered) {
  const short = toShortTopic(entry.full);
  shortCounts.set(short, (shortCounts.get(short) ?? 0) + 1);
}
for (const entry of discovered) {
  const short = toShortTopic(entry.full);
  const usable =
    short !== entry.full &&
    shortCounts.get(short) === 1 &&
    !fullSlugs.has(short) &&
    !docs.has(short);
  const topic = usable ? short : entry.full;
  docs.set(topic, {
    path: entry.path,
    summary: firstMeaningfulLine(readFileSync(entry.path, 'utf8')),
  });
}

const missing = REQUIRED_TOPICS.filter((topic) => !docs.has(topic));
if (missing.length > 0) {
  throw new Error(`Required MCP doc topics are missing: ${missing.join(', ')}`);
}

const identifier = (topic) =>
  `${topic.replace(/-([a-z0-9])/g, (_match, char) => char.toUpperCase())}Doc`;
const escapeForTemplate = (text) =>
  text.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

const ordered = [...docs.entries()].sort(
  ([left], [right]) =>
    (PRIORITY.get(left) ?? 100) - (PRIORITY.get(right) ?? 100) || left.localeCompare(right),
);

const banner =
  '// GENERATED by scripts/embed-docs.mjs — do not edit by hand.\n' +
  '// Every markdown file under docs/ (plus the README) is embedded automatically on build.\n\n';

const bodies = ordered
  .map(
    ([topic, meta]) =>
      `export const ${identifier(topic)} = \`${escapeForTemplate(readFileSync(meta.path, 'utf8'))}\`;\n`,
  )
  .join('\n');

const index = `
/** Every embedded topic: slug -> { summary, doc }. */
export const EMBEDDED_DOCS = {
${ordered
  .map(
    ([topic, meta]) =>
      `  '${topic}': { summary: ${JSON.stringify(meta.summary)}, doc: ${identifier(topic)} },`,
  )
  .join('\n')}
} as const;
`;

writeFileSync(resolve(here, '..', 'src', 'generated', 'docs.ts'), banner + bodies + index);
console.log(`embedded ${ordered.length} doc topics: ${ordered.map(([topic]) => topic).join(', ')}`);
